Capability to process images as part of multipart message body
jamesboswell/thold-slack pull request #2
Opened 2017-05-11 09:28 UTC by bbouffaut

Add the capability to process images embedded into multipart messages body:
- add a multipart message type test in current get_image function
- put current get_image function content into return_image function
- return_image function is called either image is in attachments or in body parts

NB:
- the current version only process JPEG image
- in case of multiple images in body, only retrieve the first one

2017-05-12 21:39 UTC, jamesboswell commented
Merci @bbouffaut   I will try to review in the next few days, I have a lot going on right now.  soyez patient š'il vous plaît

2017-05-23 18:24 UTC, jamesboswell requested changes
This looks pretty neat!  Thank you @bbouffaut   Can you please make the suggested changes?
I need to do a bit of testing, and then I can accept.

2017-05-23 18:24 UTC, jamesboswell commented on thold-slack.py
> +        #print("Message is multipart") #DEBUG
@bbouffaut can we remove the DEBUG lines please?

2017-05-23 18:24 UTC, jamesboswell commented on thold-slack.py
> +        #print("Message is not multipart but has attachement") #DEBUG
Remove DEBUG

2017-05-23 18:24 UTC, jamesboswell commented on thold-slack.py
> +    '''UPDATE BBO: extract the image data from the part provided as argument: either part of multipart message, either attachement'''
Remove BBO please
```
'''Extract the image data from the part provided as argument: either part of multipart message, either attachment'''```

2017-05-23 18:24 UTC, jamesboswell commented on thold-slack.py
> +        if 'image/jpg' in part_or_attachement.get_content_type():
Anglais form  `attachment` s'il vous plait

2017-05-23 18:24 UTC, jamesboswell commented on thold-slack.py
> +            open(imgfile, 'wb').write(part_or_attachement.get_payload(decode=True))
`attachment`

2017-06-29 19:00 UTC, merged

2017-06-29 20:37 UTC, bbouffaut commented
Hi @jamesboswell ! Fix is done, and update is pushed. Thanks for your feedback.